### ISSUE TITLE
timed actions -1 second

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#452]
Sometimes when I do a temporary action like `tempmute` or `tempban` and the time is - lets say - two hours (`2h`) the message shows `1 hour 59 minutes 59 seconds` which is pretty annoying if you try to format those messages in a complete different way than usual.

Why does BM not take the time given directly from the command for the message?

This issue existing since BM4 when I remember correctly.

BM 5.7.1

**Comment by Kakifrucht** [comment]
This probably has to do with the fact that the time you enter is parsed and then transformed, after the async worker is done, instead of directly taking your input. I personally find this annoying too, and would like to have it changed.
This also caused bans that ocurred before the summer clock time change to add 1 hour to the ban, making it look even weirder.

**Comment by confuser** [comment]
As @Kakifrucht said, it's to do with the asynchronous nature of BM. By the time the ban is entered into the database etc, time has progressed since the time the command was ran. This makes it a little difficult to fix, as it's currently performing as intended.

**Comment by manuelgu** [comment]
Couldn't you just format the input string and display it to the sender rather? So when you enter `/tempmute johndoe 2h #reason` it will actually mute him for `1 hour 59 minutes 59 seconds` but tell the sender `2 hours`.

**Comment by EvilOlaf** [comment]
I am not really deep into Java, honestly not really at all but as far as my technical understanding should not it should be possible to get the time diff argument from the command and put it to a variable and when the async worker finished use this variable to build the message string that will be shown ingame from it?

Please correct me if I am totally wrong :)

**Comment by confuser** [comment]
This may have been fixed with the fix for #497

**Comment by EvilOlaf** [comment]
Uuuuhh that might be so awesome.

**Comment by EvilOlaf** [comment]
Nope. Just issued a tempban for 30 days and received 29 days and 23 hours.

**Comment by EvilOlaf** [comment]
Still an issue. Just banned someone for 1 day and got "23 hours, 59 minutes and 59 seconds".

**Comment by Kakifrucht** [comment]
Can confirm.

**Comment by EvilOlaf** [comment]
Another confirmed situation. Banned for 4 minutes and 59 seconds.

**Comment by confuser** [comment]
Noted

**Comment by EvilOlaf** [comment]
No idea if something has been changed that could be related. If not, sorry for the bump.

`for 4 weeks 1 day 23 hours 59 minutes 59 seconds`
Supposed to be 30 days or calculated in BM four weeks and two days.

**Comment by confuser** [comment]
```
[08:09:08 INFO]: confuser has been temporarily banned for 2 days by Console for Testing a
tempban confuser 2h Tes
[08:09:27 INFO]: confuser has been temporarily banned for 2 hours by Console for Tes
tempban confuser 30d test
[08:10:05 INFO]: confuser has been temporarily banned for 1 month by Console for test
```

Unfortunately I can't seem to replicate this locally

**Comment by sigmaroot** [comment]
Try to replicate it **ingame** and with **cpu load**.

**Comment by Kakifrucht** [comment]
This is certainly still the case, I get this a couple of times.

**Comment by sigmaroot** [comment]
Should be fixed with #676

**Comment by EvilOlaf** [comment]
Uuuhhh can't wait for release <3
